# Practice with Lambda Functions

In [1]:
#Group4 - MTH, Thorn, Aung Kyaw Moe

Cconvert the following simple functions to lambda functions.

In [2]:
def Get_First_Letter(name):
    """Take a name as input return the lowercase
    first letter of the name"""
    if name[0] == "J":
        first_letter = name[0].lower()
        return first_letter
    else:
        last_letter = name[-1]
        return last_letter


Get_First_Letter("Steve")

'e'

In [3]:
#Define your lambda function here
f = lambda name: name[0].lower() if name[0] == "J" else name[-1]
f("Steve")

'e'

In [4]:
def Check_Even(x):
    """Return True if x is even and odd otherwise """

    return x%2 == 0

Check_Even(5)

False

In [5]:
#Define your lambda function here
g = lambda x: x%2 == 0
g(5)

False

In [7]:
def Get_Num(L):
    """Return the integer version of the number
    specified by the list if strings in L"""

    return int("".join(L))

Get_Num(["1","5","2"])

152

In [6]:
#Define your lambda function here
l = lambda L: int("".join(L))
l(["1","5","2"])

152

# Filtering in pandas

In this practice, we will explore data on the progression of salaries of students graduating from various schools. The file "salaries-by-region.csv" gives this information broken down by region and the the file "salaries-by-college-type.csv" gives this information broken by school type.

In [10]:
import pandas as pd

def Get_Dict_Region(file_location):
    """Take as input the file location of salaries-by-region.csv
    and returns a dictionary with a key for each school whose value is the region
    of that school."""

    df_region = pd.read_csv(file_location)
    region_dict = {}
    for index, row in df_region.iterrows():
        region_dict[row['School Name']] = row['Region']
    return region_dict

$--------------------------------------------------$

Write the function Get_Dict_Region, which reads the file "salaries-by-region.csv" into a dataframe called df_region and then uses iterrows() to construct a dictionary where there is a key for each school and it's value is the region.  Return this dictionary.

In [11]:
import pandas as pd

#Write your code here
file_path  = "/content/salaries-by-region.csv"
D_regions = Get_Dict_Region(file_path)

In [13]:
list(D_regions.items())[:5]

[('Stanford University', 'California'),
 ('California Institute of Technology (CIT)', 'California'),
 ('Harvey Mudd College', 'California'),
 ('University of California, Berkeley', 'California'),
 ('Occidental College', 'California')]

Read in the file "salaries-by-college-type.csv" into a a dataframe called df_college_type and use dtype to check the how each column is stored. Use "N/A" as the na_values when you read in the dataframe.

In [15]:
#Write your code here
df_college_type = pd.read_csv('/content/salaries-by-college-type.csv', na_values='N/A')
display(df_college_type.dtypes)

School Name                          object
School Type                          object
Starting Median Salary               object
Mid-Career Median Salary             object
Mid-Career 10th Percentile Salary    object
Mid-Career 25th Percentile Salary    object
Mid-Career 75th Percentile Salary    object
Mid-Career 90th Percentile Salary    object
dtype: object

We need notice that all of the salary categories are objects when they should be ints. Use a for loop over the columns attribute of the dataframe df_college_type and an apply function to do the conversion of each of these columns to a float.

In [16]:
#Write your code here
salary_columns = [
    'Starting Median Salary',
    'Mid-Career Median Salary',
    'Mid-Career 10th Percentile Salary',
    'Mid-Career 25th Percentile Salary',
    'Mid-Career 75th Percentile Salary',
    'Mid-Career 90th Percentile Salary'
]

for col in salary_columns:
    if col in df_college_type.columns:
        df_college_type[col] = df_college_type[col].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).apply(lambda x: float(x) if x.strip() != '' else None)

display(df_college_type.dtypes)
display(df_college_type.head())

School Name                           object
School Type                           object
Starting Median Salary               float64
Mid-Career Median Salary             float64
Mid-Career 10th Percentile Salary    float64
Mid-Career 25th Percentile Salary    float64
Mid-Career 75th Percentile Salary    float64
Mid-Career 90th Percentile Salary    float64
dtype: object

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),Engineering,72200.0,126000.0,76800.0,99200.0,168000.0,220000.0
1,California Institute of Technology (CIT),Engineering,75500.0,123000.0,NaN,104000.0,161000.0,NaN
2,Harvey Mudd College,Engineering,71800.0,122000.0,NaN,96000.0,180000.0,NaN
3,"Polytechnic University of New York, Brooklyn",Engineering,62400.0,114000.0,66800.0,94300.0,143000.0,190000.0
4,Cooper Union,Engineering,62200.0,114000.0,NaN,80200.0,142000.0,NaN

**Then** use map and a lambda function to add a column for region.

In [18]:
#Write you code here
df_college_type['Region'] = df_college_type['School Name'].map(lambda x: D_regions.get(x))
display(df_college_type.head())

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary,Region
0,Massachusetts Institute of Technology (MIT),Engineering,72200.0,126000.0,76800.0,99200.0,168000.0,220000.0,Northeastern
1,California Institute of Technology (CIT),Engineering,75500.0,123000.0,NaN,104000.0,161000.0,NaN,California
2,Harvey Mudd College,Engineering,71800.0,122000.0,NaN,96000.0,180000.0,NaN,California
3,"Polytechnic University of New York, Brooklyn",Engineering,62400.0,114000.0,66800.0,94300.0,143000.0,190000.0,Northeastern
4,Cooper Union,Engineering,62200.0,114000.0,NaN,80200.0,142000.0,NaN,Northeastern

How many school-dept pairs have a starting salary greater than 65K?

In [19]:
#Write your code here
salaries_above_65k = df_college_type[df_college_type['Starting Median Salary'] > 65000]
num_schools_above_65k = len(salaries_above_65k)
print(f"Number of school-dept pairs with a starting salary greater than 65K: {num_schools_above_65k}")

Number of school-dept pairs with a starting salary greater than 65K: 4

What is the average median starting salary among these schools?

In [20]:
#Write your code here
average_starting_salary = salaries_above_65k['Starting Median Salary'].mean()
print(f"The average median starting salary among these schools is: ${average_starting_salary:,.2f}")

The average median starting salary among these schools is: $71,500.00

What is the median mid career 75th percentile salary of party schools in a Southern or Western region?

In [21]:
#Filter for 'Party School' in 'School Type'
party_schools = df_college_type[df_college_type['School Type'] == 'Party School']

#Filter for Southern or Western regions
southern_western_party_schools = party_schools[party_schools['Region'].isin(['Southern', 'Western'])]

#Calculate the median mid-career 75th percentile salary
median_salary = southern_western_party_schools['Mid-Career 75th Percentile Salary'].median()

print(f"The median mid-career 75th percentile salary of party schools in a Southern or Western region is: ${median_salary:,.2f}")

The median mid-career 75th percentile salary of party schools in a Southern or Western region is: $nan

What fraction of California schools have a starting median starting salary above 50K?

In [23]:
# Filter for California schools
california_schools = df_college_type[df_college_type['Region'] == 'California']

# Filter California schools with starting median salary above 50K
salaries_above_50k_california = california_schools[california_schools['Starting Median Salary'] > 50000]

# Calculate the fraction
if not california_schools.empty:
    fraction = len(salaries_above_50k_california) / len(california_schools)
    print(f"Fraction of California schools with a starting median salary above 50K: {fraction:.2f}")
else:
    print("No California schools found in the dataset.")

Fraction of California schools with a starting median salary above 50K: 0.41

How many schools have university in their name?

In [24]:
num_university_schools = df_college_type[df_college_type['School Name'].str.contains('University', case=False, na=False)].shape[0]
print(f"Number of schools with 'University' in their name: {num_university_schools}")

Number of schools with 'University' in their name: 211