# Pandas - Part 1

Pandas will be the primary library that we use for the data analytics section of the course.  It contains high-level data structures and manipulation tools designed to make data analysis fast and easy in Python.  The core data structures that we will use are pandas series and dataframes. In this part we cover:

- Reading/Writing from/to a csv file.
- Getting basic properties of the dataframe.
- Indexing and Slicing dataframes

## Reading csv + Basic Attributes

In [1]:
import pandas as pd

#How we read in a pandas dataframe. The header=0 means column names are in the first row
df=pd.read_csv("/content/Grades.csv", header=0)

#The head method returns the first five rows
df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

In [2]:
#There are column names
df.columns

Index(['Name', 'Previous_Part', 'Participation1', 'Mini_Exam1', 'Mini_Exam2',
       'Participation2', 'Mini_Exam3', 'Final', 'Grade'],
      dtype='object')

In [3]:
#And there are row names
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [4]:
#Get the dimensions of the data frame with shape
dimensions = df.shape
numRows = dimensions[0]
numCols = dimensions[1]
numCols

9

In [5]:
#Get the data type of each column
df.dtypes

Name               object
Previous_Part     float64
Participation1      int64
Mini_Exam1        float64
Mini_Exam2        float64
Participation2      int64
Mini_Exam3        float64
Final             float64
Grade              object
dtype: object

In [6]:
#We can pick out a column by referencing its name. The result is a series or one dimensional data frame
df['Name'].head()

0     Jake
1      Joe
2    Susan
3      Sol
4    Chris
Name: Name, dtype: object

In [7]:
#You can similarly pick out columns as attributes with the '.'
df.Grade.head()

0     A
1     A
2    A-
3     A
4     A
Name: Grade, dtype: object

When you pick out a single column as we have done above the result is a series, which is essentially a one-dimensional dataframe

In [8]:
name_column = df["Name"]

name_column.head()

0     Jake
1      Joe
2    Susan
3      Sol
4    Chris
Name: Name, dtype: object

In [9]:
#We index and slice a series through the index
name_column[0:3]

0     Jake
1      Joe
2    Susan
Name: Name, dtype: object

Note that when we slice a series, the second entry in non-inclusive.

In [13]:
#You can pick out multiple columns by specifying a list of column names
name_grade_final = df[['Name', 'Grade']].head()

In [14]:
#Here is how we write a dataframe
name_grade_final.to_csv("Name_Grade.csv")

When we pick out multiple column, as we have done above, the result is dataframe.

## Slicing and Indexing

We will be using the .loc (just labels) approach.  You can also slice with .iloc (just indicies) or .ix (indices and labels).

In [15]:
#Let's look at the data
df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

In [16]:
#Pick out a single entry
df.loc[3,"Name"]

'Sol'

In [17]:
#Select contiguous rows and columns
df.loc[1:3, "Mini_Exam3":"Grade"]

   Mini_Exam3  Final Grade
1        14.0   32.0     A
2        10.5   33.0    A-
3        13.0   34.0     A

In [18]:
#Select non-contiguous rows and columns
df.loc[[0,2,4], "Mini_Exam3":"Grade"]

   Mini_Exam3  Final Grade
0        10.0   33.0     A
2        10.5   33.0    A-
4        12.5   33.5     A

Note that when we slice with .loc, the endpoint are inclusive.

In [19]:
#Select none continuguous rows
df.loc[[0,2,4], ["Previous_Part","Grade"]]

   Previous_Part Grade
0           32.0     A
2           30.0    A-
4           30.0     A

# Pandas - Part 2

In this part, we will cover:

- Useful built in column methods.
- Creating new columns and deleting existing ones.
- **Bonus**: Dealing with date-time columns.

In [21]:
#Read in the data frame
df=pd.read_csv("/content/Grades.csv", header=0)

df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

In [22]:
#Compute mean of Final column
avg_final = df["Final"].mean()
avg_final

np.float64(31.81578947368421)

We can convert the type of a column using the **astype()** method.

In [23]:
#Returns the Participation 1 column as a float
df["Participation1"].astype("float64").head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: Participation1, dtype: float64

In [24]:
#Change Participation 1 column
df["Participation1"] = df["Participation1"].astype("float64")
#Note that df has changed and the two Participation column are different
df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1.0,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1.0,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1.0,19.0,17.0,1,12.5,33.5,A

In [25]:
df.dtypes

Name               object
Previous_Part     float64
Participation1    float64
Mini_Exam1        float64
Mini_Exam2        float64
Participation2      int64
Mini_Exam3        float64
Final             float64
Grade              object
dtype: object

Note that the two participation columns have different types because of our conversion.

The **unique()** method returns an array (think of it as a list) of the unique values in the column

In [26]:
#Let's look at how many unique grades there were
list_grades = df["Grade"].unique()

list_grades

array(['A', 'A-', 'B', 'B+', 'A+', 'B-', 'C+'], dtype=object)

In [27]:
#We can slice list_grades just like a list
list_grades[1:3]

array(['A-', 'B'], dtype=object)

The **value_counts()** method returns the counts of each unique value in the column as a series

In [28]:
grade_breakdown = df["Grade"].value_counts()
grade_breakdown

Grade
A     8
B     3
A-    2
B+    2
C+    2
A+    1
B-    1
Name: count, dtype: int64

In [29]:
#Recall that we slice series through their index
grade_breakdown["A"]

np.int64(8)

We can apply any of these built in functions to multiple columns.

In [30]:
#applying function to multiple rows
df[["Final", "Mini_Exam3"]].mean()

Final         31.815789
Mini_Exam3    10.526316
dtype: float64

As you can see, the end result is a series, where the column names become the index of the series. The **describe()** method gives you key stats (as a dataframe) for every numeric column.

In [31]:
#Using the describe() method
summary = df.describe()
summary

,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final
count,19.000000,19.000000,19.000000,19.000000,19.0,19.000000,19.000000
mean,29.500000,0.947368,18.026316,17.052632,1.0,10.526316,31.815789
std,2.848001,0.229416,3.360199,2.753254,0.0,2.796196,4.913729
min,22.000000,0.000000,7.000000,12.000000,1.0,5.500000,21.000000
25%,28.500000,1.000000,17.500000,15.500000,1.0,9.000000,31.000000
50%,30.000000,1.000000,19.000000,18.000000,1.0,10.000000,32.000000
75%,31.500000,1.000000,20.000000,19.000000,1.0,12.750000,34.000000
max,33.000000,1.000000,22.000000,21.000000,1.0,17.000000,42.000000

We can index and slice the above dataframe like any other dataframe.

In [35]:
#slicing summary dataframe
summary.loc[["min", "max"], ["Final", "Previous_Part"]]  #Similar to non-continuous one eg.[0,2,4]

     Final  Previous_Part
min   21.0           22.0
max   42.0           33.0

Next, we look at how to create new columns

In [36]:
#Create a New Column that is a function of other columns
df["Final_Perc"] = df["Final"]/35
df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Final_Perc
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A,0.942857
1,Joe,32.0,1.0,20.0,16.0,1,14.0,32.0,A,0.914286
2,Susan,30.0,1.0,19.0,19.0,1,10.5,33.0,A-,0.942857
3,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A,0.971429
4,Chris,30.0,1.0,19.0,17.0,1,12.5,33.5,A,0.957143

In [37]:
#I can then delete it with the drop method
df.drop(["Final_Perc"], inplace = True, axis=1)
df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1.0,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1.0,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1.0,19.0,17.0,1,12.5,33.5,A

The inplace argument works as follows:

 - inplace = True : The dataframe itself will have the given column(s) deleted.
 - inplace = False: Will return a dataframe with the column(s) deleted.

 The axis argument works as follows:

 - axis = 1 : delete columns given
 - axis = 0 : delete rows given.

 Let's look at an example where we delete rows

In [38]:
#Delete rows with index 0 and 2
drop_rows = df.drop([0,2], inplace = False, axis=0)
drop_rows.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
1,Joe,32.0,1.0,20.0,16.0,1,14.0,32.0,A
3,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1.0,19.0,17.0,1,12.5,33.5,A
5,Tarik,31.0,1.0,19.0,19.0,1,8.0,24.0,B
6,Malik,31.5,1.0,20.0,21.0,1,9.0,36.0,A

Let's have a look at df

In [39]:
df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1.0,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1.0,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1.0,19.0,17.0,1,12.5,33.5,A

Note that df was not changed! This is what happens when you set inplace.

Let's see how we can sort a data frame.  The inplace argument has the same affect as the drop method.

In [40]:
#Sort the data frame according tothe Final Column
#By setting inplace= False will just return the sorted dataframe and not chnage df
df.sort_values(by = ["Final"], inplace =False, ascending=False).head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
8,Ronaldo,33.0,1.0,20.0,20.0,1,17.0,42.0,A+
9,Messi,30.5,1.0,17.0,18.0,1,9.0,37.0,A-
6,Malik,31.5,1.0,20.0,21.0,1,9.0,36.0,A
17,Vik,31.5,1.0,15.0,19.0,1,13.0,35.0,A
12,Charlie,32.0,1.0,20.0,17.0,1,11.0,34.0,A

Now let's sort by multiple columns, specifying more than one column is essentially specifying a tie break

In [41]:
#Sort by Mini Exam 1 and tie breal with Previous Part

result_sorted = df.sort_values(by = ["Mini_Exam1", "Previous_Part"], inplace =False, ascending=False)
result_sorted.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
3,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A
8,Ronaldo,33.0,1.0,20.0,20.0,1,17.0,42.0,A+
1,Joe,32.0,1.0,20.0,16.0,1,14.0,32.0,A
12,Charlie,32.0,1.0,20.0,17.0,1,11.0,34.0,A
6,Malik,31.5,1.0,20.0,21.0,1,9.0,36.0,A



Now let's dive into the datetime column type with Parking data set, where each row corresponds to a different parking ticket given in NYC.

In [43]:
#Read in parking and let's have a look.
df_parking = pd.read_csv("/content/Parking.csv")
df_parking.head()

   Unnamed: 0 Registration_State    Issue_Date Vehicle_Make
0           0                 NY  6/30/16 2:17        TOYOT
1           1                 NY   7/4/16 1:18        ME/BE
2           2                 NY  7/11/16 6:15        LINCO
3           3                 NY   7/4/16 1:10        NISSA
4           4                 NY   7/1/16 6:30        VOLKS

I don't like having that Unnamed column. I can fix this by telling pandas that I want that column to be the index instead of a separate column.

In [44]:
#Read in parking and specify column that will serve as index
df_parking = pd.read_csv("/content/Parking.csv", index_col=0)
df_parking.head()

  Registration_State    Issue_Date Vehicle_Make
0                 NY  6/30/16 2:17        TOYOT
1                 NY   7/4/16 1:18        ME/BE
2                 NY  7/11/16 6:15        LINCO
3                 NY   7/4/16 1:10        NISSA
4                 NY   7/1/16 6:30        VOLKS

Now let's have a look at how pandas read in each column

In [45]:
#look at how each column is stored
df_parking.dtypes

Registration_State    object
Issue_Date            object
Vehicle_Make          object
dtype: object

I want Issue_Date to be a datetime and not a string! Let's convert it.

In [46]:
#Reset the column Issue Date to be a datetime
df_parking["Issue_Date"] = pd.to_datetime(df_parking["Issue_Date"])

#Now its a datetime object
df_parking.dtypes

/tmp/ipykernel_1700/2628000260.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_parking["Issue_Date"] = pd.to_datetime(df_parking["Issue_Date"])

Registration_State            object
Issue_Date            datetime64[ns]
Vehicle_Make                  object
dtype: object

Let's look at the first entry of this column, that is now a datetime column

In [47]:
first_entry = df_parking.loc[0,"Issue_Date"]
first_entry

Timestamp('2016-06-30 02:17:00')

We see that it is a timestamp.  Timestamps have lots of nice attributes that we can extract.

In [48]:
#Get the day
first_entry.day

30

In [49]:
#Get the month
first_entry.month

6

In [52]:
#We can get the weekday name
first_entry.day_name()

'Thursday'

In [53]:
#We can even see if the year is a leap year
first_entry.is_leap_year

True

If we want to get these attributes for an entire column, then we have to throw in a .dt

In [55]:
#Get the day of the week for the entire column
all_dow = df_parking["Issue_Date"].dt.day_name()
all_dow.head()

0    Thursday
1      Monday
2      Monday
3      Monday
4      Friday
Name: Issue_Date, dtype: object

In [58]:
#Lets add this column in
df_parking["DOW"] = df_parking["Issue_Date"].dt.day_name()
df_parking.head()

  Registration_State          Issue_Date Vehicle_Make       DOW
0                 NY 2016-06-30 02:17:00        TOYOT  Thursday
1                 NY 2016-07-04 01:18:00        ME/BE    Monday
2                 NY 2016-07-11 06:15:00        LINCO    Monday
3                 NY 2016-07-04 01:10:00        NISSA    Monday
4                 NY 2016-07-01 06:30:00        VOLKS    Friday

In [59]:
#Let's see the most frequent days for parking tickets
df_parking["DOW"].value_counts()

DOW
Thursday     81
Tuesday      80
Friday       73
Sunday       73
Wednesday    68
Monday       64
Saturday     60
Name: count, dtype: int64

In [60]:
#We can even do time arithmetic.  We get a TimeDelta object
delta = df_parking.Issue_Date.max() - df_parking.Issue_Date.min()
delta

Timedelta('753 days 09:21:00')

In [61]:
#We can pull out attributes
delta.seconds, delta.days

(33660, 753)

In [62]:
#Lets say I wanted to subtract 5 hours from the first parking ticket
firstTicket = df_parking.loc[0,"Issue_Date"]

#We can create a TimeDelta Object
timeDiff = pd.Timedelta(hours = 5)

print(firstTicket)
print(firstTicket - timeDiff)

2016-06-30 02:17:00
2016-06-29 21:17:00

# Pandas - Part 3

In this part, we will a collection of important miscellaneous concepts that include:

- Changing columns names
- Combining dataframes
- Understanding the index
- Missing Data
- Reading from Excel

In [63]:
import pandas as pd

#Read in the data frame
df=pd.read_csv("/content/Grades.csv", header=0)

df.head()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

Recall that we can get the column names through the attribute column

In [64]:
#Get the column names
df.columns

Index(['Name', 'Previous_Part', 'Participation1', 'Mini_Exam1', 'Mini_Exam2',
       'Participation2', 'Mini_Exam3', 'Final', 'Grade'],
      dtype='object')

We can change column names through the rename method

In [65]:
#Change the column names
df.rename(columns={"Participation1":"Participation_1", "Participation2":"Participation_2"}, inplace=True)

df.head()

,Name,Previous_Part,Participation_1,Mini_Exam1,Mini_Exam2,Participation_2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

The format for the columns input is {"old_column_name":"new_column_name"}. It should be noted that the rename method can also be applied to change the index by changing columns to index.

Let's try to better understand the index or row labels.  Currently, for the dataframe df, the index is just the row numbers.  But what happens if we want to access the Sol's row? As it stands, we would have to remeber that Sol is in row 3.

Another approach is to make the Names column the index.

In [66]:
#Setting the column Name to be the index
df.set_index("Name", inplace = True)

df.head()

,Previous_Part,Participation_1,Mini_Exam1,Mini_Exam2,Participation_2,Mini_Exam3,Final,Grade
Name,,,,,,,,
Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

 The inplace = True command will change the dataframe df.  Now the Name column is our index and we can access Sol's info as easily as:

In [67]:
#Access Sol's info
df.loc["Sol",:]

Previous_Part      31.0
Participation_1       1
Mini_Exam1         22.0
Mini_Exam2         13.0
Participation_2       1
Mini_Exam3         13.0
Final              34.0
Grade                 A
Name: Sol, dtype: object

When setting the index, make sure you choose a column that will uniquely identify each row.

We can change the the index back to row numbers using the reset_index() method.

In [68]:
#Resetting the index
df.reset_index(drop=False, inplace=True)
df.head()

,Name,Previous_Part,Participation_1,Mini_Exam1,Mini_Exam2,Participation_2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

Now we are back to the original data frame. Setting drop = False (default) adds the old index as a new column in the dataframe instead of just deletiing it.

Next, we see how to combine or concatenate two (or more) data frames.

In [69]:
#I can combine data frames with concat function
head = df.head()
tail = df.tail()

In [70]:
#Have a look at the variable head
head

,Name,Previous_Part,Participation_1,Mini_Exam1,Mini_Exam2,Participation_2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A

In [71]:
#Have a look at the variable head
tail

,Name,Previous_Part,Participation_1,Mini_Exam1,Mini_Exam2,Participation_2,Mini_Exam3,Final,Grade
14,Chrinstine,29.0,1,13.0,15.5,1,9.0,31.0,B
15,Josh,23.5,1,17.0,12.0,1,8.5,23.0,C+
16,Jackson,28.0,1,18.0,15.5,1,7.0,31.0,B
17,Vik,31.5,1,15.0,19.0,1,13.0,35.0,A
18,Sarah,22.0,1,18.0,13.0,1,9.0,21.0,C+

In [72]:
#axis=0 says stack them top to bottom. axis =1 stacks side to side
dfConcat = pd.concat([head,tail], axis =0)
dfConcat

,Name,Previous_Part,Participation_1,Mini_Exam1,Mini_Exam2,Participation_2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A
14,Chrinstine,29.0,1,13.0,15.5,1,9.0,31.0,B
15,Josh,23.5,1,17.0,12.0,1,8.5,23.0,C+
16,Jackson,28.0,1,18.0,15.5,1,7.0,31.0,B
17,Vik,31.5,1,15.0,19.0,1,13.0,35.0,A
18,Sarah,22.0,1,18.0,13.0,1,9.0,21.0,C+

So the concat method takes a list of dataframes as the first input and also an axis input for whether you want to stock top to bottom or side to side. Note that after we stack, the index is messed up.  Let's use the reset_index method to change the index back to row numbers.

In [73]:
dfConcat.reset_index(inplace= True, drop=True)

dfConcat

,Name,Previous_Part,Participation_1,Mini_Exam1,Mini_Exam2,Participation_2,Mini_Exam3,Final,Grade
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A
1,Joe,32.0,1,20.0,16.0,1,14.0,32.0,A
2,Susan,30.0,1,19.0,19.0,1,10.5,33.0,A-
3,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A
4,Chris,30.0,1,19.0,17.0,1,12.5,33.5,A
5,Chrinstine,29.0,1,13.0,15.5,1,9.0,31.0,B
6,Josh,23.5,1,17.0,12.0,1,8.5,23.0,C+
7,Jackson,28.0,1,18.0,15.5,1,7.0,31.0,B
8,Vik,31.5,1,15.0,19.0,1,13.0,35.0,A
9,Sarah,22.0,1,18.0,13.0,1,9.0,21.0,C+

## Handling Missing Data

Missing data is common in most data analysis applications.  You have a number of options for filtering out missing data.  One option is doing it by hand or you can use the *dropna* method.

With dataframes objects, things get a little more complex.  You may want to drop rows or columns which are all NA or just those containing any NAs. *dropna* by default drops any row containing a missing value.

In [75]:
#Here we have two pieces of missing data
df_missing = pd.read_csv("/content/Missing_Data.csv")
df_missing

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1,19.5,20,1,10.0,33.0,A,-1
1,Joe,NaN,1,20.0,16,1,14.0,32.0,A,23
2,Sol,31.0,1,22.0,13,1,13.0,34.0,A,34
3,Chris,30.0,-1,19.0,not available,1,12.5,33.5,A,72

The isnull() method returns a series or dataframe of booleans corresponding to whether the particular entries are null or not.

In [76]:
#isnull method for a data frame
df_missing.isnull()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False

We can make sure they are all read in as NA values using the na_values input when we read in the file

In [78]:
#Notice that here the not available is turned into an NaN value
df_missing_NA = pd.read_csv("/content/Missing_Data.csv", na_values=["NaN", "not available"])
df_missing_NA

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1,19.5,20.0,1,10.0,33.0,A,-1
1,Joe,NaN,1,20.0,16.0,1,14.0,32.0,A,23
2,Sol,31.0,1,22.0,13.0,1,13.0,34.0,A,34
3,Chris,30.0,-1,19.0,NaN,1,12.5,33.5,A,72

In [79]:
#Let's rerun the isnull() method on the Previous_Part column
df_missing_NA.Previous_Part.isnull()

0    False
1     True
2    False
3    False
Name: Previous_Part, dtype: bool

In [80]:
#Now on the entire dataframe
df_missing_NA.isnull()

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False

Let's say we now realize that the -1 in the Participation column is a NA value.  If we add -1 to the na_values input, we will also replace the -1 in the Temp column. Luckily, we can give a dictionary to the na_values input which specifies the NA values in each columns

In [82]:
#Note that the temp column is unaffected
df_missing_NA2 = pd.read_csv("/content/Missing_Data.csv",\
                na_values={"Previous_Part":"NA", "Participation1":-1,"Mini_Exam2":"not available"})
df_missing_NA2

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A,-1
1,Joe,NaN,1.0,20.0,16.0,1,14.0,32.0,A,23
2,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A,34
3,Chris,30.0,NaN,19.0,NaN,1,12.5,33.5,A,72

Now lets see how we can change/replace these NA values

In [83]:
#Get rid of all rows with an NA
df_missing_NA2.dropna(axis=0)

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A,-1
2,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A,34

In [84]:
#Passing how='all' will only drop rows that are all NA (doesn't change anything)
df_missing_NA2.dropna(how='all')

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A,-1
1,Joe,NaN,1.0,20.0,16.0,1,14.0,32.0,A,23
2,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A,34
3,Chris,30.0,NaN,19.0,NaN,1,12.5,33.5,A,72

In [85]:
#Dropping column is just a matter of passing axis=1 (doesn't change anything)
df_missing_NA2.dropna(axis=1,how='all')

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A,-1
1,Joe,NaN,1.0,20.0,16.0,1,14.0,32.0,A,23
2,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A,34
3,Chris,30.0,NaN,19.0,NaN,1,12.5,33.5,A,72

Rather than filtering ou missing data, you may want to fill in the "holes" in any number of ways. For most purposes, the *fillna* method with a constant relplaces missing values with that value.

In [86]:
df_missing_NA2.fillna(0)

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A,-1
1,Joe,0.0,1.0,20.0,16.0,1,14.0,32.0,A,23
2,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A,34
3,Chris,30.0,0.0,19.0,0.0,1,12.5,33.5,A,72

In [87]:
#You can pass fillna a dict which gives the replacement value for each column
df_missing_NA2.fillna({"Previous_Part":5,"Mini_Exam2":0.5})

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1.0,19.5,20.0,1,10.0,33.0,A,-1
1,Joe,5.0,1.0,20.0,16.0,1,14.0,32.0,A,23
2,Sol,31.0,1.0,22.0,13.0,1,13.0,34.0,A,34
3,Chris,30.0,NaN,19.0,0.5,1,12.5,33.5,A,72

With *fillna* you can do lots of things with a little creativity.  For example, you might pass the mean of median value of a series.

In [89]:
#Replace with mean
df_missing_NA2.fillna(df_missing_NA2.select_dtypes(include='number').mean())

,Name,Previous_Part,Participation1,Mini_Exam1,Mini_Exam2,Participation2,Mini_Exam3,Final,Grade,Temp
0,Jake,32.0,1.0,19.5,20.000000,1,10.0,33.0,A,-1
1,Joe,31.0,1.0,20.0,16.000000,1,14.0,32.0,A,23
2,Sol,31.0,1.0,22.0,13.000000,1,13.0,34.0,A,34
3,Chris,30.0,1.0,19.0,16.333333,1,12.5,33.5,A,72

## Excel Files (.xlsx)

We can use the read_excel/write_excel method, which both take a sheet name as input. You can use string formatting to access the correct sheet.  Lets say I want to read in the the workbook titled "Excel_Reading.xlsx" and add in averages at the end of each column.

In [91]:
#Read in an excel file
df1 = pd.read_excel("/content/Excel_Reading.xlsx", "Sheet1")
df1

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

       1000      5000      10000
0   0.030399  0.023484  0.023118
1    0.02369  0.022857  0.023055
2   0.029339  0.023260  0.022905
3   0.027113  0.025012  0.023738
4   0.026462  0.023854  0.023733
5  Not avail  0.024979  0.023728
6   0.028853  0.023676  0.022813
7   0.024345  0.022929  0.023441
8        NaN  0.023021  0.022286
9   0.025326  0.024034  0.023799

In [93]:
#We can replace NAs with na_values as we did before
df1 = pd.read_excel("/content/Excel_Reading.xlsx", "Sheet1", na_values = ["NA", "Not avail"])
df1

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

      1000      5000      10000
0  0.030399  0.023484  0.023118
1  0.023690  0.022857  0.023055
2  0.029339  0.023260  0.022905
3  0.027113  0.025012  0.023738
4  0.026462  0.023854  0.023733
5       NaN  0.024979  0.023728
6  0.028853  0.023676  0.022813
7  0.024345  0.022929  0.023441
8       NaN  0.023021  0.022286
9  0.025326  0.024034  0.023799

In [94]:
#Fill with mean
df1.fillna(df1.mean())

      1000      5000      10000
0  0.030399  0.023484  0.023118
1  0.023690  0.022857  0.023055
2  0.029339  0.023260  0.022905
3  0.027113  0.025012  0.023738
4  0.026462  0.023854  0.023733
5  0.026941  0.024979  0.023728
6  0.028853  0.023676  0.022813
7  0.024345  0.022929  0.023441
8  0.026941  0.023021  0.022286
9  0.025326  0.024034  0.023799

In [95]:
#We can write the file with to_excel. We can specify a start row and column
df1.to_excel("NewFile.xlsx", "Sheet1", startrow=5, startcol=5)

/tmp/ipykernel_1700/1964290760.py:2: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  df1.to_excel("NewFile.xlsx", "Sheet1", startrow=5, startcol=5)